# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fa95b9c69c65f9952541dcfc1d9388a739846496b44f50e9c9d00bd9fcbc89ee447fdf0415c49bbe471ad43a417fc1595bc3560fa47938a11f430e99739cad9

test:
  secret_key_base: d3ad64866c3836637611deeef4f3eca8bb6bc8441b6133a6fb157784fa37613fe7f1aa9214616ed8735dd538bbb5b1acf13349a7a0c5047e17fc98feddceb537

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
